license="LGPL-3.0"
#issueTrackerURL=""

[[mods]]
modId="mendingrework"
version="0.3"
displayName="Mending Rework"

#displayURL=""
logoFile="mendingrework.png"
#credits=""

authors="Dusk"
description='''Repair items without experience.\n\n
Mod Feature List:\n
- Repairing items in anvils costs 0 experience and does not increase future combine costs.\n
- Chance of anvil taking damage on use reduced by half.\n
- Mending enchant no longer repairs items with experience.\n
- Items with mending regain more durability when repaired and will never damage an anvil when renaming or repairing.\n
- Unbreaking enchant uses the same formula on armor as on items (armor will last longer).\n
- Netherite items are repaired with diamonds or netherite scraps instead of netherite ingots.\n
- Tridents are repaired with diamonds, crossbows with iron, bows and fishing rods with string.\n
- If an item doesn't have a set repair material it defaults to Bottle O' Enchanting.\n'''

[[mixins]]
config="mendingrework.mixins.json"